[package]
name = "koperatiff-command-api"
version = "0.1.0"
authors = ["Berkan <yavrib@gmail.com>"]

[dependencies]
actix = "0.5"
actix-web = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
dotenv = "0.11.0"
